/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppVouchersBookingIdRouteImport } from './routes/app.vouchers.$bookingId'
import { Route as AppBookingsBookingIdRouteImport } from './routes/app.bookings.$bookingId'
import { Route as AppBookingsBookingIdSupportRouteImport } from './routes/app.bookings.$bookingId.support'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersBookingIdRoute = AppVouchersBookingIdRouteImport.update({
  id: '/vouchers/$bookingId',
  path: '/vouchers/$bookingId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsBookingIdRoute = AppBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AppBookingsRoute,
} as any)
const AppBookingsBookingIdSupportRoute =
  AppBookingsBookingIdSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AppBookingsBookingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRouteWithChildren
  '/app/vouchers/$bookingId': typeof AppVouchersBookingIdRoute
  '/app/bookings/$bookingId/support': typeof AppBookingsBookingIdSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRouteWithChildren
  '/app/vouchers/$bookingId': typeof AppVouchersBookingIdRoute
  '/app/bookings/$bookingId/support': typeof AppBookingsBookingIdSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookings': typeof AppBookingsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/bookings/$bookingId': typeof AppBookingsBookingIdRouteWithChildren
  '/app/vouchers/$bookingId': typeof AppVouchersBookingIdRoute
  '/app/bookings/$bookingId/support': typeof AppBookingsBookingIdSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bookings'
    | '/app/login'
    | '/app/profile'
    | '/app/bookings/$bookingId'
    | '/app/vouchers/$bookingId'
    | '/app/bookings/$bookingId/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/bookings'
    | '/app/login'
    | '/app/profile'
    | '/app/bookings/$bookingId'
    | '/app/vouchers/$bookingId'
    | '/app/bookings/$bookingId/support'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bookings'
    | '/app/login'
    | '/app/profile'
    | '/app/bookings/$bookingId'
    | '/app/vouchers/$bookingId'
    | '/app/bookings/$bookingId/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers/$bookingId': {
      id: '/app/vouchers/$bookingId'
      path: '/vouchers/$bookingId'
      fullPath: '/app/vouchers/$bookingId'
      preLoaderRoute: typeof AppVouchersBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$bookingId': {
      id: '/app/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/app/bookings/$bookingId'
      preLoaderRoute: typeof AppBookingsBookingIdRouteImport
      parentRoute: typeof AppBookingsRoute
    }
    '/app/bookings/$bookingId/support': {
      id: '/app/bookings/$bookingId/support'
      path: '/support'
      fullPath: '/app/bookings/$bookingId/support'
      preLoaderRoute: typeof AppBookingsBookingIdSupportRouteImport
      parentRoute: typeof AppBookingsBookingIdRoute
    }
  }
}

interface AppBookingsBookingIdRouteChildren {
  AppBookingsBookingIdSupportRoute: typeof AppBookingsBookingIdSupportRoute
}

const AppBookingsBookingIdRouteChildren: AppBookingsBookingIdRouteChildren = {
  AppBookingsBookingIdSupportRoute: AppBookingsBookingIdSupportRoute,
}

const AppBookingsBookingIdRouteWithChildren =
  AppBookingsBookingIdRoute._addFileChildren(AppBookingsBookingIdRouteChildren)

interface AppBookingsRouteChildren {
  AppBookingsBookingIdRoute: typeof AppBookingsBookingIdRouteWithChildren
}

const AppBookingsRouteChildren: AppBookingsRouteChildren = {
  AppBookingsBookingIdRoute: AppBookingsBookingIdRouteWithChildren,
}

const AppBookingsRouteWithChildren = AppBookingsRoute._addFileChildren(
  AppBookingsRouteChildren,
)

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppProfileRoute: typeof AppProfileRoute
  AppVouchersBookingIdRoute: typeof AppVouchersBookingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppProfileRoute: AppProfileRoute,
  AppVouchersBookingIdRoute: AppVouchersBookingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
